#!/data/data/com.termux/files/usr/bin/bash

bar_width=30
filesize=400  # MB
download_speed=21  # MBps
filename="ÇR4ZY_KÏLLÁR_2.sh"

echo -e "\e[1;31m ⚠️ DISCLAIMER ⚠️\e[0m"
echo -e "\e[1mThis is a Fake Virus script to Prank your friends :D.
All downloads and scripts are fake and only made for fun.\e[0m"
sleep 5

clear
for i in {1..3}; do
    for dots in "." ".." "..."; do
        echo -ne "Executing Command$dots   \r"
        sleep 0.5
    done
done

clear
cat << "EOF"




 @@@@@                                        @@@@@
@@@@@@@                                      @@@@@@@
@@@@@@@           @@@@@@@@@@@@@@@            @@@@@@@
 @@@@@@@@       @@@@@@@@@@@@@@@@@@@        @@@@@@@@
     @@@@@     @@@@@@@@@@@@@@@@@@@@@     @@@@@
       @@@@@  @@@@@@@@@@@@@@@@@@@@@@@  @@@@@
         @@  @@@@@@@@@@@@@@@@@@@@@@@@@  @@
            @@@@@@@    @@@@@@    @@@@@@
            @@@@@@      @@@@      @@@@@
            @@@@@@      @@@@      @@@@@
             @@@@@@    @@@@@@    @@@@@
              @@@@@@@@@@@  @@@@@@@@@@
               @@@@@@@@@@  @@@@@@@@@
           @@   @@@@@@@@@@@@@@@@@   @@
           @@@@  @@@@ @ @ @ @ @@@@  @@@@
          @@@@@   @@@ @ @ @ @ @@@   @@@@@
        @@@@@      @@@@@@@@@@@@@      @@@@@
      @@@@          @@@@@@@@@@@          @@@@
   @@@@@              @@@@@@@              @@@@@
  @@@@@@@                                 @@@@@@@
   @@@@@                                   @@@@@

ÇR4ZY_KÏLLÁR_2 VIRUS BY xXFinFin99872Xx😈
EOF

sleep 3
echo ""
echo -e "\e[1;35mPick:\e[0m"
sleep 2

select choice in "YES😈" "NO👿"; do
    case $REPLY in
        1)
            echo -e "\nOK..."
            sleep 2
            echo "say goodbye😈"
            sleep 1

            # Fake progress bar
            for i in $(seq 1 100); do
                percent=$i
                filled=$((i * bar_width / 100))
                empty=$((bar_width - filled))
                downloaded=$((filesize * i / 100))

                bar=$(printf "%0.s=" $(seq 1 $filled))
                bar+=">"
                bar+=$(printf "%0.s " $(seq 1 $empty))

                scroll_idx=$((i % (${#filename} - 4)))
                scroll_name="${filename:scroll_idx:5}"

                printf "\r\e[36m%s \e[0m|[%s]| \e[33m%3d%% \e[32m%5dMB \e[34m%dMB/s\e[0m" "$scroll_name" "$bar" "$percent" "$downloaded" "$download_speed"
                sleep 0.15
            done

            echo -e "\n\e[32mDownload Completed.\e[0m"
            sleep 1.5

            for i in {1..3}; do
                for dots in "." ".." "..."; do
                    echo -ne "Executing $filename$dots   \r"
                    sleep 0.5
                done
            done

            clear
            echo -e "\e[1;32mNungguin ya... XD\e[0m"
            break
            ;;
        2)
            echo -e "\n\e[31mYou will regret this...\e[0m"
            sleep 2
            break
            ;;
        *)
            echo -e "\e[33mInvalid choice 🗿\e[0m"
            ;;
    esac
done
